services:
  # MASS Simulator (Haberleşme Ünitesi)
  mass-simulator:
    build: .
    container_name: mass-simulator
    ports:
      - "8000:8000"  # HTTP API
    environment:
      - MQTT_BROKER=192.168.1.20
      - MQTT_PORT=1883
      - MQTT_USERNAME=guest
      - MQTT_PASSWORD=guest
      - DEVICE_FLAG=SIM
      - DEVICE_SERIAL=SIM001ABCDE12345
      - DEVICE_BRAND=SimulatorBrand
      - DEVICE_MODEL=SimV1.0
      - FIRMWARE=1.01
      - TOPIC_TO_SERVER=mass/device/response
      - TOPIC_FROM_SERVER=mass/device/request/${DEVICE_FLAG}/${DEVICE_SERIAL}
      - HEARTBEAT_INTERVAL=60
      - API_PORT=8000
    restart: unless-stopped